name: Upload To S3

on:
  push:
    branches:
      - main
    paths:
      - 'config/app.config'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  S3_BUCKET: python-config-eu-west-1
  CONFIG_FILE: config/app.config

jobs:
  upload-config:
    name: Upload app.config to S3
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::195231312458:role/Github-action-oidc-aws
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-S3ConfigUpload

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Upload app.config to S3
        run: |
          aws s3 cp \
            "${{ env.CONFIG_FILE }}" \
            "s3://${{ env.S3_BUCKET }}/app.config"

      - name: Verify S3 object
        run: |
          aws s3 ls \
            "s3://${{ env.S3_BUCKET }}/app.config"
