name: Test AWS OIDC

on:
  push:
    branches:
      - main
    paths:
      - 'config/app.config'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Show OIDC IDs
        run: |
          echo "Repository Owner ID: ${{ github.repository_owner_id }}"
          echo "Repository ID: ${{ github.repository_id }}"
          echo "Repository: ${{ github.repository }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::195231312458:role/Github-action-oidc-aws
          aws-region: eu-west-1
          role-session-name: GitHubActions-S3ConfigUpload

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity
