name: Upload Config to S3

on:
  push:
    branches:
      - master
    paths:
      - 'config/app.config'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  S3_BUCKET: python-config-eu-west-1
  CONFIG_FILE: config/app.config

jobs:
  upload-config:
    name: Upload app.config to S3
    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------
      # 1. Checkout repository
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v5

      # --------------------------------------------------
      # 2. Show changed config
      # --------------------------------------------------
      - name: Verify config file
        run: |
          echo "Config file:"
          ls -lh ${{ env.CONFIG_FILE }}

          echo "Config content:"
          cat ${{ env.CONFIG_FILE }}

      # --------------------------------------------------
      # 3. Authenticate to AWS using GitHub OIDC
      # --------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::195231312458:role/github-wf-oidc-s3fullaccess
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-S3ConfigUpload

      # --------------------------------------------------
      # 4. Verify AWS identity
      # --------------------------------------------------
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      # --------------------------------------------------
      # 5. Upload config file to S3
      # --------------------------------------------------
      - name: Upload app.config to S3
        run: |
          aws s3 cp \
            "${{ env.CONFIG_FILE }}" \
            "s3://${{ env.S3_BUCKET }}/app.config"

      # --------------------------------------------------
      # 6. Verify uploaded file
      # --------------------------------------------------
      - name: Verify S3 object
        run: |
          aws s3 ls \
            "s3://${{ env.S3_BUCKET }}/app.config"
